name: Build and Deploy to EKS

on: 
  workflow_dispatch:
    

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: comercial-k8s-apps
  EKS_CLUSTER_NAME: eks-commercial-study
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write   # necessário para autenticação OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::547320736290:role/github-actions-cicd-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login on Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag & push of image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./App
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Update image in manifest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" manifests/deployment.yaml

      - name: Apply manifest to EKS
        run: |
          kubectl apply -f manifests/deployment.yaml
          kubectl apply -f manifests/service.yaml

      - name: Debug
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/my-app --timeout=120s

      - name: Verify rollout
        id: verify-rollout
        run: |
          kubectl rollout status deployment/my-app --timeout=120s

      - name: Debug Deployment Failure
        if: failure() && steps.verify-rollout.outcome == 'failure'
        run: |
          echo "  Deployment failed! Starting automatic diagnostics..."
          
          echo -e "\n [1/3] PODS STATUS:"
          kubectl get pods
          
          echo -e "\n [2/3] DEPLOYMENT DETAILS AND EVENTS:"
          kubectl describe deployment/my-app
          
          echo -e "\n [3/3] RECENT EVENTS FROM FAILING PODS:"
          # Fetches recent events to expose ImagePullBackOff or CrashLoopBackOff reasons
          kubectl get events --sort-by='.metadata.creationTimestamp' | tail -n 20
          
          echo -e "\n [BONUS] LATEST CONTAINER LOGS (if any are running):"
          kubectl logs deployment/my-app --all-containers=true --tail=30 || echo "Could not fetch container logs."